export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const SEND_ANSWER = 'SEND_ANSWER';
export const SEND_ANSWER_SUCCESS = 'SEND_ANSWER_SUCCESS';
